applications/home/urls.py
from django.urls import path

from . import views

app_name = 'home_app'

urlpatterns = [
	path('panel/', views.HomePage.as_view(), name = 'panel'),
	path('mixin/', views.TemplatePruebaMixin.as_view(), name = 'mixin'),
]

applications/users/urls.py
from django.urls import path

from . import views

app_name = 'users_app'

urlpatterns = [
	path('register/', views.UserRegisterView.as_view(), name = 'user-register'),
	path('login/', views.LoginUser.as_view(), name = 'user-login'),
	path('logout/', views.LogoutView.as_view(), name = 'user-logout'),
	path('update/', views.UpdatePasswordView.as_view(), name = 'user-update'),
	path('verification/<pk>/', views.CodeVerificationView.as_view(), name = 'user-verification'),
]

login/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
]

applications/home/models.py
from django.db import models

# Create your models here.

applications/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):
	GENDER_CHOICES = (
		('M', 'Masculino'),
		('F', 'Femenino'),
	)

	username = models.CharField(max_length = 10, unique = True)
	email = models.EmailField()
	nombres = models.CharField(max_length = 30, blank=True)
	apellidos = models.CharField(max_length = 30, blank=True)
	gener = models.CharField(max_length = 1, choices=GENDER_CHOICES, blank=True)
	codregistro = models.CharField(max_length = 6, blank = True)

	is_staff = models.BooleanField(default = False)
	is_active = models.BooleanField(default = False)

	USERNAME_FIELD = 'username'

	REQUIRED_FIELDS = ['email',]

	objects = UserManager()

	def get_short_name(self):
		return self.username

	def get_full_name(self):
		return self.nombres + ' ' + self.apellidos

applications/users/forms.py
from django import forms
from django.contrib.auth import authenticate

from .models import User

class UserRegisterForm(forms.ModelForm):

	password1 = forms.CharField(
		label = 'Contraseña',
		required = True,
		widget = forms.PasswordInput(
			attrs = {
				'placeholder': 'Contraseña'
			}
		)	
	)

	password2 = forms.CharField(
		label = 'Contraseña',
		required = True,
		widget = forms.PasswordInput(
			attrs = {
				'placeholder': 'Repetir Contraseña'
			}
		)	
	)

	class Meta:
		model = User
		fields = (
			'username',
			'email',
			'nombres',
			'apellidos',
			'gener'
		)

		def clean_password2(self):
			if self.cleaned_data['password1'] != self.cleaned_data['password2']:
				self.add_error('password2', 'Las contraseñas son distintas')

class LoginForm(forms.Form):
	username = forms.CharField(
		label = 'Username',
		required = True,
		widget = forms.TextInput(
			attrs = {
				'placeholder': 'username'
			}
		)	
	)

	password = forms.CharField(
		label = 'Contraseña',
		required = True,
		widget = forms.PasswordInput(
			attrs = {
				'placeholder': 'Contraseña'
			}
		)	
	)

	def clean(self):
		cleaned_data = super(LoginForm, self).clean()

		username = self.cleaned_data['username']
		password = self.cleaned_data['password']

		if not authenticate(username = username, password = password):
			raise forms.ValidationError('Usuario y/o Contraseña incorrectos')

		return self.cleaned_data

class UpdatePasswordForm(forms.Form):

	password1 = forms.CharField(
		label = 'Contraseña',
		required = True,
		widget = forms.PasswordInput(
			attrs = {
				'placeholder': 'Contraseña actual'
			}
		)	
	)

	password2 = forms.CharField(
		label = 'Contraseña Nueva',
		required = True,
		widget = forms.PasswordInput(
			attrs = {
				'placeholder': 'Contraseña nueva'
			}
		)	
	)

class VerificationForm(forms.Form):
	codregistro = forms.CharField(required = True)

	def __init__(self, pk, *args, **kwargs):
		self.id_user = pk
		super(VerificationForm, self).__init__(*args, **kwargs)

	def clean_codregistro(self):
		codigo = self.cleaned_data['codregistro']

		if len(codigo) == 6:
			activo = User.objects.cod_validation(self.id_user, codigo)

			if not activo:
				raise forms.ValidationError('El código es incorrecto')

		else:
			raise forms.ValidationError('El código es incorrecto')

applications/home/views.py
import datetime
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import (
	TemplateView
)

class HomePage(LoginRequiredMixin, TemplateView):
	template_name = 'home/index.html'

	login_url = reverse_lazy('users_app:user-login')

class FechaMixin(object):

	def get_context_data(self, **kwargs):
		context = super(FechaMixin, self).get_context_data(**kwargs)
		context['fecha'] = datetime.datetime.now()
		return context

class TemplatePruebaMixin(FechaMixin, TemplateView):
	template_name = 'home/mixin.html'

applications/users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.views.generic.edit import FormView

from .forms import UserRegisterForm, LoginForm, UpdatePasswordForm, VerificationForm

from .models import User

from .functions import code_generator

class UserRegisterView(FormView):
	template_name = 'users/register.html'
	form_class = UserRegisterForm
	success_url = '/'

	def form_valid(self, form):

		codigo = code_generator()

		usuario = User.objects.create_user(
			form.cleaned_data['username'],
			form.cleaned_data['email'],
			form.cleaned_data['password1'],
			nombres = form.cleaned_data['nombres'],
			apellidos = form.cleaned_data['apellidos'],
			gener = form.cleaned_data['gener'],
			codregistro = codigo,
		)

		asunto = 'Confirmación de email'
		mensaje = f'Código de verificación: {codigo}'
		email_remitente = 'contacto.sventas.svc@gmail.com'

		send_mail(asunto, mensaje, email_remitente, [form.cleaned_data['email'],])



		return HttpResponseRedirect(
			reverse(
				'users_app:user-verification',
				kwargs = {'pk': usuario.id}
			)
		)

class LoginUser(FormView):
	template_name = 'users/login.html'
	form_class = LoginForm
	success_url = reverse_lazy('home_app:panel')

	def form_valid(self, form):
		user = authenticate(
			username = form.cleaned_data['username'],
			password = form.cleaned_data['password']
		)
		login(self.request, user)
		return super(LoginUser, self).form_valid(form)

class LogoutView(View):

	def get(self, request, *args, **kwargs):
		logout(request)

		return HttpResponseRedirect(
			reverse(
				'users_app:user-login'
			)
		)

class UpdatePasswordView(LoginRequiredMixin, FormView):
	template_name = 'users/update.html'
	form_class = UpdatePasswordForm
	success_url = reverse_lazy('users_app:user-login')

	login_url = reverse_lazy('users_app:user-login')

	def form_valid(self, form):

		usuario = self.request.user

		user = authenticate(
			username = usuario.username,
			password = form.cleaned_data['password1']
		)

		if user:
			new_password = form.cleaned_data['password2']
			usuario.set_password(new_password)
			usuario.save()

		logout(self.request)
		return super(UpdatePasswordView, self).form_valid(form)

class CodeVerificationView(FormView):
	template_name = 'users/verification.html'
	form_class = VerificationForm
	success_url = reverse_lazy('users_app:user-login')

	def get_form_kwargs(self):
		kwargs = super(CodeVerificationView, self).get_form_kwargs()
		kwargs.update({
			'pk': self.kwargs['pk']
			})
		return kwargs

	def form_valid(self, form):

		User.objects.filter(
			id = self.kwargs['pk']
		).update(
			is_active = True
		)

		return super(CodeVerificationView, self).form_valid(form)

templates/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/foundation.min.css' %}">
	{% block cssfields %}
		
	{% endblock cssfields %}
</head>
<body>
<div class="top-bar">
	<div class="top-bar-left">
		<ul class="dropdown menu" data-dropdown-menu>
			<li class="menu-text">SVentas</li>
			<li><a href="{% url 'home_app:panel' %}">Home</a></li>
			<li><a href="#">Two</a></li>
			<li><a href="#">Three</a></li>
		</ul>
	</div>
	<div class="top-bar-right">
		<ul class="menu">
			<li><input type="search" placeholder="Search"></li>
			<li><button type="button" class="button">Search</button></li>
		</ul>
	</div>
</div>
	{% block content %}

	{% endblock content %}
</body>
</html>

templates/home/index.html
{% extends "base.html" %}

{% block title %}
	Sistema
{% endblock title %}

{% block cssfields %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
{% endblock cssfields %}

{% block content %}
	<h4 id="title-register">Panel de usuarios</h4>
	<ul>
		<li><a href="{% url 'users_app:user-logout' %}">Cerrar Sesión</a></li>
		<li><a href="{% url 'users_app:user-update' %}">Actualizar Datos</a></li>
	</ul>
{% endblock content %}

templates/home/mixin.html
{% extends "base.html" %}

{% block title %}
	Mixin
{% endblock title %}

{% block content %}
	{{ fecha }}
{% endblock content %}

templates/users/login.html
{% extends "base.html" %}

{% block title %}
	Login
{% endblock title %}

{% block cssfields %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
{% endblock cssfields %}

{% block content %}
	<h4 id="title-register">Login</h4>

	<div class="grid-x">
		<div class="cell large-3" id="div1"></div>
		<form method="post" class="cell large-5" id="form-login">{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Acceder</button>
		</form>
		<div class="cell large-3 div2"></div>
	</div>
{% endblock content %}

templates/users/register.html
{% extends "base.html" %}

{% block title %}
	Registro
{% endblock title %}

{% block cssfields %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
{% endblock cssfields %}

{% block content %}
	<div class="grid-x">

		<div class="cell large-5 grid-x">
			<h4 class="cell large-5" id="title-register">Registro de Usuarios</h4>
		</div>
	</div>
	<form method="post" id="form-login">{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Enviar</button>
	</form>
{% endblock content %}

templates/users/update.html
{% extends "base.html" %}

{% block title %}
	Cambiar Contraseña
{% endblock title %}

{% block cssfields %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
{% endblock cssfields %}

{% block content %}
	<h4 id="title-register">Cambiar Contraseña</h4>

	<div class="grid-x">
		<div class="cell large-3" id="div1"></div>
		<form method="post" class="cell large-5" id="form-login">{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Acceder</button>
		</form>
		<div class="cell large-3 div2"></div>
	</div>
{% endblock content %}

templates/users/verification.html
{% extends "base.html" %}

{% block title %}
	Verificación Código
{% endblock title %}

{% block cssfiles %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="css/app.css">
{% endblock cssfiles %}

{% block content %}
	<h4 id="title-register">Verificación de email</h4>

	<div class="grid-x">
		<div class="cell large-3" id="div1"></div>
		<form method="post" class="cell large-5" id="form-login">{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Enviar</button>
		</form>
		<div class="cell large-3 div2"></div>
	</div>
{% endblock content %}